services:
    lifemem-postgres:
        image: postgres:18
        container_name: lifemem-postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: lifemem
        volumes:
            - lifemem_dev_pgdata:/var/lib/postgresql
        ports:
            - '5432:5432'

    lifemem-redis:
        image: redis:alpine
        container_name: lifemem-redis
        ports:
            - '6379:6379'

    lifemem-minio:
        image: minio/minio:RELEASE.2025-04-22T22-12-26Z-cpuv1
        container_name: lifemem-minio
        ports:
            - '9000:9000'
            - '9001:9001'
        volumes:
            - lifemem_dev_minio_data:/data
        environment:
            MINIO_ROOT_USER: minio
            MINIO_ROOT_PASSWORD: miniopassword
        command: server --console-address ":9001" /data
        restart: unless-stopped

volumes:
    lifemem_dev_pgdata:
    lifemem_dev_minio_data:
