export const entryLocationPrompts = {
    peoplePlacesDetect: [
        'Extract people and places from the note and link them to the user dictionary.',
        '',
        'Workflow: identify entities → search dictionary → prefer one clear existing match → return structured JSON only.',
        '',
        'People:',
        '- Extract real people, not generic roles unless the role refers to a specific person.',
        '- Role phrases map to known people. Example: dictionary has "девушка Даша", note says "моя девушка" → search and link if exactly one clear match.',
        '- Same for мама/папа/друг/подруга/коллега/etc. If ambiguous, do not guess.',
        '- Resolve obvious name variants/diminutives (Саша/Александр, Катя/Екатерина) when search returns one clear match.',
        '- Merge all mentions of the same person into ONE entity. Never duplicate a person because they are mentioned by different names, roles, or multiple times.',
        '- Prefer the most informative name: "девушка Даша", "подруга Маша", "мама", "друг Саша".',
        '- If a specific person is identified only by role, use the role as name.',
        '- New person not found by search → exists=false, id=null.',
        '',
        'Places:',
        '- Extract concrete locations relevant to the note: named venues, personal place labels (дом/офис/работа), parks, cafes, restaurants, streets, cities, etc.',
        '- Prefer the MOST SPECIFIC location. If a specific place is inside a city/region/country, return ONLY the specific place.',
        '- Example: "я был в музее Атлас в Москве" → ["музей Атлас"]. NOT ["музей Атлас", "Москва"].',
        '- Example: "гулял в парке Зарядье в Москве" → ["парк Зарядье"]. NOT ["парк Зарядье", "Москва"].',
        '- Example: "был в Москве, потом поехал в Санкт-Петербург" → ["Москва", "Санкт-Петербург"].',
        '- Keep multiple places only when they are genuinely separate locations or visits.',
        '- Do not extract a parent location when it only provides context for a more specific place.',
        '- Merge duplicate mentions and aliases of the same place into ONE entity.',
        '- Do not create separate entities for a venue and its address/city unless they represent genuinely different locations.',
        '- Extract a place only when the text indicates the user was there, went there, lives/works there, or otherwise clearly refers to it as a relevant location. Do not extract places mentioned only as unrelated context.',
        '- Link known places if search finds one clear match.',
        '- New place not found by search → exists=false, id=null.',
        '- Never invent or output coordinates (latitude/longitude). Do not include coords in the result.',
        '',
        'NOT places:',
        '- Weather / conditions: солнечно, дождливо, холодно, жарко, пасмурно.',
        '- Moods / qualities: весело, грустно, красиво, рядом, далеко.',
        '- Time expressions: утром, вчера, летом, сегодня.',
        '- Generic activities/nouns without a concrete location: прогулка, встреча, поездка, день.',
        '- Generic geographic context that is only a parent of an extracted specific place.',
        '',
        'Critical rules:',
        '- Never invent entities.',
        '- Never duplicate the same person or place.',
        '- Prefer one specific entity over its parent location.',
        '- exists=true only when a real dictionary search id confirms the match.',
        '- exists=false ⇒ id=null.',
        '- If multiple dictionary results are plausible, do not guess; create a new entity instead.',
        '- When uncertain whether something is a person/place, do not extract it.',
        '',
        'When you are ready to answer (no more tool calls), output ONLY the JSON value required by the format instructions — no prose.'
    ].join('\n'),

    parallelToolSearch: [
        'CRITICAL tool-calling rule:',
        'Call search_people and/or search_places in ONE assistant turn — not sequentially across turns.',
        'Each tool accepts queries: string[] — pass ALL candidate fragments in that single call.',
        'Examples:',
        '- search_people({ queries: ["Даша", "мама", "Саша"] })',
        '- search_places({ queries: ["Москва", "Питер", "Зарядье"] })',
        'Do NOT make one tool call per query. Batch every useful name/place/role variant into the arrays.',
        'If both people and places are needed, emit both tools together in the same turn, each with its full queries array.',
        'After receiving the results, produce the final answer without additional search turns unless a critical miss remains.'
    ].join('\n')
} as const;
